function gradingInputRow(label,key,step,color){return `<div class="formRow gradingTimelineRow gradingTimeline-${color}" data-grading-step="${step}"><div class="gradingTimelineLabel"><span class="gradingStepCircle">${step}</span><label for="grading-${key}">${label}</label></div><span class="numberField"><input id="grading-${key}" type="number" inputmode="decimal" min="0" step="0.1" value="${appState.inspectionDetail.inputs[key].toFixed(1)}" data-grading-input="${key}"><span class="fieldUnit">lbs</span></span></div>`;}
function gradingFormulaDetails(key){
 const i=appState.inspectionDetail.inputs,r=appState.inspectionDetail.results,d=gradingFormulaDefinitions[key];
 const vars={premiumPercent:"A = Total Premium Weight\nB = Total Net Lbs. Graded",standardPercent:"A = Total Standard Weight\nB = Total Net Lbs. Graded",criticalWeakPercent:"A = Total Critical Weak Weight\nB = Total Net Lbs. Graded",softShellPercent:"A = Total Soft Shell Weight\nB = Total Net Lbs. Graded",deadPercent:"A = Total Dead Weight\nB = Total Net Lbs. Graded",undersizePercent:'A = Total Less than 3.74" Weight\nB = Total Net Lbs. Graded',barnacleTubewormPercent:"A = Total Barnacle / Tubeworm Weight\nB = Total Net Lbs. Graded",premiumBySize:"A = Premium Weight\nB = Premium + Standard Weight",standardBySize:"A = Standard Weight\nB = Premium + Standard Weight",totalReject:"A = Sum of all reject-category weights",totalNetLbsGraded:"A = Sum of all graded category weights",rejectPercent:"A = Sum of displayed reject percentages"}[key];
 const cur={totalNetLbsGraded:`${i.premium.toFixed(1)} + ${i.standard.toFixed(1)} + ${i.criticalWeak.toFixed(1)} + ${i.softShell.toFixed(1)} + ${i.dead.toFixed(1)} + ${i.undersize.toFixed(1)} + ${i.barnacleTubeworm.toFixed(1)} = ${r.totalNetLbsGraded.toFixed(1)} lbs`,totalReject:`${i.criticalWeak.toFixed(1)} + ${i.softShell.toFixed(1)} + ${i.dead.toFixed(1)} + ${i.undersize.toFixed(1)} + ${i.barnacleTubeworm.toFixed(1)} = ${r.totalReject.toFixed(1)} lbs`,premiumPercent:`${i.premium.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.premiumPercent.toFixed(2)}%`,standardPercent:`${i.standard.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.standardPercent.toFixed(2)}%`,criticalWeakPercent:`${i.criticalWeak.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.criticalWeakPercent.toFixed(2)}%`,softShellPercent:`${i.softShell.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.softShellPercent.toFixed(2)}%`,deadPercent:`${i.dead.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.deadPercent.toFixed(2)}%`,undersizePercent:`${i.undersize.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.undersizePercent.toFixed(2)}%`,barnacleTubewormPercent:`${i.barnacleTubeworm.toFixed(1)} ÷ ${r.totalNetLbsGraded.toFixed(1)} × 100 = ${r.barnacleTubewormPercent.toFixed(2)}%`,premiumBySize:`${i.premium.toFixed(1)} ÷ (${i.premium.toFixed(1)} + ${i.standard.toFixed(1)}) × 100 = ${r.premiumBySize.toFixed(2)}%`,standardBySize:`${i.standard.toFixed(1)} ÷ (${i.premium.toFixed(1)} + ${i.standard.toFixed(1)}) × 100 = ${r.standardBySize.toFixed(2)}%`,rejectPercent:`${r.rejectPercent.toFixed(2)}%`}[key];
 const variableValues={premiumPercent:{A:i.premium.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},standardPercent:{A:i.standard.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},criticalWeakPercent:{A:i.criticalWeak.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},softShellPercent:{A:i.softShell.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},deadPercent:{A:i.dead.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},undersizePercent:{A:i.undersize.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},barnacleTubewormPercent:{A:i.barnacleTubeworm.toFixed(1),B:r.totalNetLbsGraded.toFixed(1)},premiumBySize:{A:i.premium.toFixed(1),B:(i.premium+i.standard).toFixed(1)},standardBySize:{A:i.standard.toFixed(1),B:(i.premium+i.standard).toFixed(1)}}[key]||{};
 const displayFormula={premiumPercent:"A ÷ B × 100",standardPercent:"A ÷ B × 100",criticalWeakPercent:"A ÷ B × 100",softShellPercent:"A ÷ B × 100",deadPercent:"A ÷ B × 100",undersizePercent:"A ÷ B × 100",barnacleTubewormPercent:"A ÷ B × 100",premiumBySize:"A ÷ B × 100",standardBySize:"A ÷ B × 100"}[key]||d.formula;
 const currentHtml={
   premiumPercent:`<span class="formulaValue formulaVarA">${i.premium.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.premiumPercent.toFixed(2)}%`,
   standardPercent:`<span class="formulaValue formulaVarA">${i.standard.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.standardPercent.toFixed(2)}%`,
   criticalWeakPercent:`<span class="formulaValue formulaVarA">${i.criticalWeak.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.criticalWeakPercent.toFixed(2)}%`,
   softShellPercent:`<span class="formulaValue formulaVarA">${i.softShell.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.softShellPercent.toFixed(2)}%`,
   deadPercent:`<span class="formulaValue formulaVarA">${i.dead.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.deadPercent.toFixed(2)}%`,
   undersizePercent:`<span class="formulaValue formulaVarA">${i.undersize.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.undersizePercent.toFixed(2)}%`,
   barnacleTubewormPercent:`<span class="formulaValue formulaVarA">${i.barnacleTubeworm.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${r.totalNetLbsGraded.toFixed(1)}</span> × 100 = ${r.barnacleTubewormPercent.toFixed(2)}%`,
   premiumBySize:`<span class="formulaValue formulaVarA">${i.premium.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${(i.premium+i.standard).toFixed(1)}</span> × 100 = ${r.premiumBySize.toFixed(2)}%`,
   standardBySize:`<span class="formulaValue formulaVarA">${i.standard.toFixed(1)}</span> ÷ <span class="formulaValue formulaVarB">${(i.premium+i.standard).toFixed(1)}</span> × 100 = ${r.standardBySize.toFixed(2)}%`
 }[key]||null; return {...d,formula:displayFormula,variables:vars,current:cur,currentHtml,variableValues};
}
function fbtn(text,key){return `<button type="button" class="resultCellButton" data-grading-formula="${key}">${text}</button>`;}
function gradingResultsTable(){const i=appState.inspectionDetail.inputs,r=appState.inspectionDetail.results;return `<div class="resultsTableWrap"><table class="resultsTable gradingTable"><thead><tr><th>Grade</th><th>Net Lbs.<br>Graded</th><th>% of Net<br>Lbs.</th><th>% by<br>Size</th></tr></thead><tbody>
<tr><td>Premium</td><td>${i.premium.toFixed(1)}</td><td>${fbtn(r.premiumPercent.toFixed(2)+'%','premiumPercent')}</td><td>${fbtn(r.premiumBySize.toFixed(2)+'%','premiumBySize')}</td></tr>
<tr><td>Standard</td><td>${i.standard.toFixed(1)}</td><td>${fbtn(r.standardPercent.toFixed(2)+'%','standardPercent')}</td><td>${fbtn(r.standardBySize.toFixed(2)+'%','standardBySize')}</td></tr>
<tr><td>Critical Weak</td><td>${i.criticalWeak.toFixed(1)}</td><td>${fbtn(r.criticalWeakPercent.toFixed(2)+'%','criticalWeakPercent')}</td><td>—</td></tr>
<tr><td>Soft Shell</td><td>${i.softShell.toFixed(1)}</td><td>${fbtn(r.softShellPercent.toFixed(2)+'%','softShellPercent')}</td><td>—</td></tr>
<tr><td>Dead</td><td>${i.dead.toFixed(1)}</td><td>${fbtn(r.deadPercent.toFixed(2)+'%','deadPercent')}</td><td>—</td></tr>
<tr><td>Less than 3.74&quot;</td><td>${i.undersize.toFixed(1)}</td><td>${fbtn(r.undersizePercent.toFixed(2)+'%','undersizePercent')}</td><td>—</td></tr>
<tr><td>Barn. / Tubeworm</td><td>${i.barnacleTubeworm.toFixed(1)}</td><td>${fbtn(r.barnacleTubewormPercent.toFixed(2)+'%','barnacleTubewormPercent')}</td><td>—</td></tr>
<tr class="summaryRow"><td>Total Reject</td><td>${fbtn(r.totalReject.toFixed(1),'totalReject')}</td><td>${fbtn(r.rejectPercent.toFixed(2)+'%','rejectPercent')}</td><td>—</td></tr>
<tr class="grandRow"><td>Total Net Lbs.<br>Graded</td><td>${fbtn(r.totalNetLbsGraded.toFixed(1),'totalNetLbsGraded')}</td><td>${r.percentLbsGraded.toFixed(2)}%</td><td>${r.percentBySizeTotal.toFixed(2)}%</td></tr>
</tbody></table></div>`;}
function renderInspectionDetailWorkspace(){setWorkspaceContent(`<div class="workspaceModule"><section class="moduleCard"><header class="moduleCardHeader"><div class="moduleCardIcon" data-icon="grading"></div><div><h2 class="moduleCardTitle">Inspection Detail</h2><p class="moduleCardSubtitle">Grade sample quality & percentages</p></div></header><div class="moduleCardBody"><div class="inputList">${gradingInputRow("Gross Lbs. Graded","grossGraded",1,"blue")}${gradingInputRow("Premium","premium",2,"green")}${gradingInputRow("Standard","standard",3,"green")}${gradingInputRow("Critical Weak","criticalWeak",4,"orange")}${gradingInputRow("Soft Shell","softShell",5,"orange")}${gradingInputRow("Dead","dead",6,"red")}${gradingInputRow('Less than 3.74"',"undersize",7,"red")}${gradingInputRow("Barn. / Tubeworm","barnacleTubeworm",8,"red")}</div><div class="moduleActions"><button type="button" class="clearButton" id="clearGrading">Clear</button></div><div class="resultsHeading dataSheetHeading"><span class="resultsHeadingIcon">◉</span><span>Dockside Grading Summary</span></div><div id="gradingLiveResults">${gradingResultsTable()}</div></div></section></div>`);if(typeof renderIcons==='function')renderIcons();bindGradingSummaryWorkspace();}
function refreshGradingResultsOnly(){const p=document.getElementById("gradingLiveResults");if(p){p.innerHTML=gradingResultsTable();bindGradingFormulaButtons();}}
function bindGradingFormulaButtons(){document.querySelectorAll("[data-grading-formula]").forEach(b=>b.addEventListener("click",()=>showFormulaHelp(gradingFormulaDetails(b.dataset.gradingFormula),b)));}
function bindGradingSummaryWorkspace(){document.querySelectorAll("[data-grading-input]").forEach(input=>{input.addEventListener("focus",e=>e.target.select());input.addEventListener("input",e=>{setAppNumber("inspectionDetail",e.target.dataset.gradingInput,e.target.value);refreshGradingResultsOnly();if(typeof refreshHomePreview==="function")refreshHomePreview();});});const clear=document.getElementById("clearGrading");if(clear)clear.addEventListener("click",()=>{Object.keys(appState.inspectionDetail.inputs).forEach(k=>appState.inspectionDetail.inputs[k]=0);recalculateAll();renderInspectionDetailWorkspace();});bindGradingFormulaButtons();}
